### ISSUE TITLE
Create Discord server

### ISSUE THREAD

**Issue by Alexbruvv** [roboticsoutreach/robohack#1]
We should create a Discord server for the event with:
- General spaces to chat/ask questions
- Channels specific to each team

A bot to assign roles for each team could be useful if we have time.

**Comment by Alexbruvv** [comment]
The Discord server has been created with relevant roles and team channels.

**Comment by tpoomlmly** [comment]
What's the invite URL?

**Comment by Alexbruvv** [comment]
https://discord.gg/UapurNuBWf
