### ISSUE TITLE
Organise game design session

### ISSUE THREAD

**Issue by Alexbruvv** [roboticsoutreach/robohack#12]

**Comment by tpoomlmly** [comment]
- [x]  Email Alistair to ask if he can do it
- [x]  Email Joyce or Reena to promote it
    - [x]  Short description message
    - [x]  Ask for pizza
    - See SUCSS x Netcraft email for inspiration
    - See previous game design workshop email for inspiration

**Comment by inventor02** [comment]
@tpoomlmly needs to reply to Alistair

**Comment by tpoomlmly** [comment]
Done

**Comment by Alexbruvv** [comment]
This happened; turnout wasn't huge but the evening was enjoyable and productive.
