### ISSUE TITLE
Find out about potential sponsor funding

### ISSUE THREAD

**Issue by Alexbruvv** [roboticsoutreach/robohack#2]

**Comment by jefftheprogrammer** [comment]
Potential sponsors: 

- From George's contact
- From Robosoc's contact
- ECS (2 potential options)

**Comment by Alexbruvv** [comment]
George's contact no longer likely.

Form to guage interest has been created and will be sent out to gather numbers for RoboSoc's contact.

Email for ECS written, yet to send.

**Comment by Alexbruvv** [comment]
Funding fully confirmed 🎉

100% from ECS - approximately 50% from outreach budget (supplies to be used for Smallpeice as well), and the further 50% approved by the Head of School.

**Comment by inventor02** [comment]
yay!
