### ISSUE TITLE
Visit the venue and plan the layout

### ISSUE THREAD

**Issue by Alexbruvv** [roboticsoutreach/robohack#23]
We should visit the design studio with a tape measure and plan the layout.

With respect to the layout, we should the placement of the following:
- Arena
- 10 Team Pits
- PA System
- Robot staging
- Robot badging
- Competition services (scoring & compbox admin)
- Battery charging

**Comment by tpoomlmly** [comment]
- Arena in the centre
- 5 team pits down either side
- PA system either side of the projector screen
- Scoring in between the arena + projector screen
- Staging on the opposite side of the arena to that
