### ISSUE TITLE
Prepare and submit SUSU booking request for truss, PA & tech

### ISSUE THREAD

**Issue by Alexbruvv** [roboticsoutreach/robohack#5]

**Comment by Alexbruvv** [comment]
SUSU have confirmed that we can hire the tech but will have to transport it ourselves.

**Comment by Alexbruvv** [comment]
I have followed up with SUSU now that we have confirmed the dates, will hopefully be finalised soon.

**Comment by Alexbruvv** [comment]
A new quote has been received and it is within budget. We'll review next week and likely accept it.

**Comment by tpoomlmly** [comment]
We've reviewed the quote and swapped the Hex battens for Quad battens
